apps/extract-stack/src/sst-env.d.ts
apps/extract-stack/tsconfig.json

VSCode LSP did play well with the import style used in sst-env.d.ts

moved sst type import to tsconfig

---

apps/extract-stack/package.json
apps/extract-stack/src/create-event.ts
apps/extract-stack/src/create-message.ts
apps/extract-stack/src/events.ts
package-lock.json

Create SQS message

---

apps/extract-stack/src/create-message.ts
apps/extract-stack/src/extract-member.ts
apps/extract-stack/src/stack.ts

QueueHandler process 1 message at a time

---

packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

closes #103 
Note: missing metric additions and deletions required for metric generation

[TOOL-35] Fetch Merge Request Diffs

---

migrations/extract/0000_robust_scorpion.sql
migrations/extract/meta/0000_snapshot.json
migrations/extract/meta/_journal.json
packages/schemas/extract/src/merge-request-commits.ts

- changes the type of external_id
- generated new .sql file and snapshot

fix:merge-request-commits-schema

---

apps/extract-stack/src/extract-merge-requests.ts
packages/functions/extract/src/config.ts
packages/functions/extract/src/get-merge-requests.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

Extract MR commit to Source Control

---

apps/extract-stack/src/events.ts
apps/extract-stack/src/extract-members.ts
apps/extract-stack/src/extract-merge-requests.ts
apps/extract-stack/src/extract-repository.ts
apps/extract-stack/src/messages.ts
packages/functions/extract/src/get-repository.test.ts
packages/functions/extract/src/get-repository.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

Feat: make namespace non-optional

---

migrations/extract/0001_misty_tusk.sql
migrations/extract/meta/0001_snapshot.json
migrations/extract/meta/_journal.json
packages/schemas/extract/src/index.ts
packages/schemas/extract/src/merge-request-notes.ts

[TOOL-53] Merge Request Note Extract Schema

---

apps/extract-stack/.sst/types/index.ts
apps/extract-stack/src/create-message.ts
apps/extract-stack/src/extract-members.ts
apps/extract-stack/src/extract-merge-request-commits.ts
apps/extract-stack/src/extract-merge-request-diffs.ts
apps/extract-stack/src/extract-merge-requests.ts
apps/extract-stack/src/messages.ts
apps/extract-stack/src/queue.ts
apps/extract-stack/src/stack.ts
package-lock.json
packages/schemas/extract/src/index.ts

refactoring extract-stack

---

packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

[TOOL-59] Fetch Merge Request Notes

---

apps/extract-stack/src/events.ts
apps/extract-stack/src/extract-member-info.ts
apps/extract-stack/src/extract-members.ts
apps/extract-stack/src/extract-user-info.ts
apps/extract-stack/src/messages.ts
apps/extract-stack/src/queue.ts
apps/extract-stack/src/stack.ts
migrations/extract/0000_lowly_triton.sql
migrations/extract/meta/0000_snapshot.json
migrations/extract/meta/_journal.json
packages/functions/extract/src/get-member-info.test.ts
packages/functions/extract/src/get-member-info.ts
packages/functions/extract/src/get-members.ts
packages/functions/extract/src/get-namespace-members.ts
packages/functions/extract/src/index.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts
packages/schemas/extract/src/members.ts

Let's get more info about the users / members

---

packages/integrations/source-control/src/gitlab/index.ts

Gitlab notes work!

---

apps/extract-stack/src/extract-member-info.ts
apps/extract-stack/src/extract-members.ts
apps/extract-stack/src/extract-merge-request-commits.ts
apps/extract-stack/src/extract-merge-request-diffs.ts
apps/extract-stack/src/extract-merge-request-notes.ts
apps/extract-stack/src/extract-merge-requests.ts
apps/extract-stack/src/extract-repository.ts
apps/extract-stack/src/get-clerk-user-token.ts

Refactoring fetching clerk user tokens

---

apps/extract-stack/src/extract-namespace-members.ts
apps/extract-stack/src/messages.ts
apps/extract-stack/src/queue.ts
apps/extract-stack/src/stack.ts
packages/functions/extract/src/get-namespace-members.test.ts
packages/functions/extract/src/get-namespace-members.ts
packages/functions/extract/src/index.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

Namespace blues

---

apps/extract-stack/src/extract-merge-requests.ts
apps/extract-stack/src/messages.ts
apps/extract-stack/src/queue.ts
packages/functions/extract/src/get-merge-requests.test.ts
packages/functions/extract/src/get-merge-requests.ts

Time period for extracting data for GitLab

---

packages/functions/transform/src/set-forge-users.test.ts
packages/functions/transform/src/set-forge-users.ts

Co-authored-by: dejan-crocoder <dejan@crocoder.dev>
closes #218

[TOOL-102] forge-users from members / namespace-members

---

apps/stack/src/extract/extract-member-info.ts
apps/stack/src/extract/queue.ts
apps/stack/stacks/ExtractStack.ts
packages/functions/extract/src/get-member-info.test.ts
packages/functions/extract/src/get-member-info.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts

[TOOL-103] Users are extracted from member-info

---

packages/schemas/transform/src/seed/dimensions.ts

onConflictDoNothing added

---

apps/stack/src/extract/events.ts
apps/stack/src/extract/extract-member-info.ts
apps/stack/src/transform/transform-forge-users.ts
apps/stack/stacks/TransformStack.ts
packages/functions/transform/src/index.ts
packages/functions/transform/src/set-forge-users.test.ts
packages/functions/transform/src/set-forge-users.ts

Issues: set-forge-users expects array of member ids, but extract.memberInfo contains a single memberId
closes #231

[TOOL-110] MemberInfo Triggers Transform

---

scripts/migrate-dev.ts

Now filters locally instead of using a query so It won't attempt to drop drizzle migrations if it doesn't exist, also ignores libsql_ tables

chore: migrate-dev table name select strategy change

---

migrations/extract/0001_closed_blizzard.sql
migrations/extract/meta/0001_snapshot.json
migrations/extract/meta/_journal.json
packages/functions/extract/src/get-merge-request-notes.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/schemas/extract/src/members.ts

Extracted source for members

---

packages/integrations/source-control/src/github/index.ts

Fix: tool-113 web url

---

packages/functions/extract/src/get-merge-requests.ts

[TOOL-124] Fixing nonsense

---

migrations/crawl/0000_familiar_tyger_tiger.sql
migrations/crawl/meta/0000_snapshot.json
migrations/crawl/meta/_journal.json
migrations/extract/0000_lying_mulholland_black.sql
packages/schemas/crawl/src/crawl-events.ts
packages/schemas/crawl/src/crawls.ts
packages/schemas/crawl/src/enum-column.ts
packages/schemas/crawl/src/index.ts

Crawl Entities

---

packages/functions/transform/src/config.ts
packages/schemas/transform/src/index.ts
packages/schemas/transform/src/merge-request-facts.ts
packages/schemas/transform/src/users-junk.ts

Users have junk in their trunk

---

migrations/extract/0000_spotty_bill_hollister.sql
migrations/extract/meta/0000_snapshot.json
migrations/extract/meta/_journal.json
packages/functions/extract/src/config.ts
packages/functions/extract/src/get-timeline-events.test.ts
packages/functions/extract/src/get-timeline-events.ts
packages/functions/transform/src/config.ts
packages/integrations/source-control/src/github/index.ts
packages/integrations/source-control/src/gitlab/index.ts
packages/integrations/source-control/src/source-control.ts
packages/schemas/extract/src/timeline-events.ts

tool-140-extract-for-timeline-Events

---

migrations/extract/0000_adorable_machine_man.sql
migrations/extract/meta/0000_snapshot.json
packages/functions/extract/src/get-timeline-events.test.ts
packages/functions/extract/src/get-timeline-events.ts
packages/integrations/source-control/src/github/index.ts
packages/schemas/extract/src/timeline-events.ts

Refactored part of the fetchTimelineEvents

---

apps/stack/src/config/create-message.ts
apps/stack/src/extract/extract-member-info.ts
apps/stack/src/extract/extract-members.ts
apps/stack/src/extract/extract-merge-request-commits.ts
apps/stack/src/extract/extract-merge-request-diffs.ts
apps/stack/src/extract/extract-merge-request-notes.ts
apps/stack/src/extract/extract-merge-requests.ts
apps/stack/src/extract/extract-namespace-members.ts
apps/stack/src/extract/extract-timeline-events.ts

This will allow using more than one queue in our code

refactor: Explicit queue sender handler

---

apps/stack/src/extract/extract-repository.ts
apps/stack/src/transform/transform-timeline.ts
apps/stack/stacks/TransformStack.ts

[TOOL-176] Periodic transform

---

packages/functions/transform/src/merge-request-metrics.ts
packages/schemas/extract/src/timeline-events.ts

fix: requested-reviewer events dont break transform when requesting team reviews

---

apps/app-htmx/src/functions/fetch-repository.ts
apps/stack/.sst/types/index.ts
apps/stack/src/extract/extract-member-info.ts
apps/stack/src/extract/extract-members.ts
apps/stack/src/extract/extract-merge-request-commits.ts
apps/stack/src/extract/extract-merge-request-diffs.ts
apps/stack/src/extract/extract-merge-request-notes.ts
apps/stack/src/extract/extract-merge-requests.ts
apps/stack/src/extract/extract-namespace-members.ts
apps/stack/src/extract/extract-repository.ts
apps/stack/src/extract/extract-timeline-events.ts
apps/stack/stacks/ExtractStack.ts
packages/integrations/source-control/src/github/index.ts

chore: fetchTimelineEventsPerPage parameter

---

packages/functions/transform/src/merge-request-metrics.ts

Handover wasnt applied

---

apps/stack/src/extract/get-clerk-user-token.ts
apps/stack/stacks/ExtractStack.ts

This reverts commit 5b6490c8cb56b15cc9b018b89c4a434f1e7f93c1.

chore: Revert "chore: remove redis (#502)"
